apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: checkyourspend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: checkyourspend
    spec:
      containers:
      - name: checkyourspend
        image: registry.gitlab.com/rad1317/checkyourspend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: registry.gitlab.com
  strategy:
    type: RollingUpdate